version: '{branch}.{build}'
pull_requests:
  do_not_increment_build_number: true
skip_non_tags: false
platform: x64
image: 
   - Previous Visual Studio 2019
environment:
  APPVEYOR_RDP_PASSWORD: 'Test123#'
init:
  - cmd: git config --global core.autocrlf true
install:
  - sh: cd ..
  - sh: mkdir java
  - sh: cd java
  - sh: wget https://download.java.net/java/GA/jdk15.0.2/0d1cfde4252546c6931946de8db48ee2/7/GPL/openjdk-15.0.2_linux-x64_bin.tar.gz
  - sh: tar zxf openjdk-15.0.2_linux-x64_bin.tar.gz
  - sh: export JAVA_HOME=$(pwd)/jdk-15.0.2
  - sh: echo java home is $JAVA_HOME
  - sh: export PATH=$JAVA_HOME/bin:$PATH
  - sh: cd ../tokentool-moulinette
  - ps: cd ..
  - ps: mkdir java
  - ps: cd java
  - ps: echo $pwd
  - ps: wget https://download.java.net/java/GA/jdk15.0.2/0d1cfde4252546c6931946de8db48ee2/7/GPL/openjdk-15.0.2_linux-x64_bin.tar.gz
  - ps: tar zxf openjdk-15.0.2_linux-x64_bin.tar.gz
  - ps: export JAVA_HOME=$(pwd)/jdk-15.0.2
  - ps: Set-Variable -Name "JAVA_HOME" "$pwd/jdk-15.0.2"
  - ps: echo java home is $JAVA_HOME
  - ps: export PATH=$JAVA_HOME/bin:$PATH
  - ps: cd ../tokentool-moulinette
  - ps: sudo apt install -y fakeroot
  - ./gradlew -version
  - java -version

build_script:
  - ./gradlew build
after_build:
  - cmd: gradlew clean build createBundle -PjavaPackagerPath=../java-packager/
artifacts:
- path: build/TokenTool-*-linux.*
  name: TokenTool-Linux
- path: build/TokenTool-*-windows.*
  name: TokenTool-Windows
- path: build/TokenTool-*-mac.*
  name: TokenTool-Mac
deploy:
- provider: GitHub
  description: Release build from AppVeyor
  auth_token: $(GITHUB_RELEASE_KEY)
  draft: false
  prerelease: true
  force_update: false
  on:
    APPVEYOR_REPO_TAG: true
on_success:
  - ps: Invoke-RestMethod $env:APPVEYOR_DISCORD_WEBHOOK_SCRIPT_URL -o send.ps1
  - ps: ./send.ps1 success $env:DISCORD_URL
on_failure:
  - ps: Invoke-RestMethod $env:APPVEYOR_DISCORD_WEBHOOK_SCRIPT_URL -o send.ps1
  - ps: ./send.ps1 failure $env:DISCORD_URL
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
