version: '{branch}.{build}'
pull_requests:
  do_not_increment_build_number: true
skip_non_tags: false
platform: x64
image: 
   - Ubuntu
#   - Previous Visual Studio 2019
environment:
  #APPVEYOR_RDP_PASSWORD: 'Test123#'
  APPVEYOR_YML_DISABLE_PS_LINUX: true
init:
  - cmd: git config --global core.autocrlf true
install:
  - sh: cd ..
  - sh: curl https://download.java.net/java/ga/jdk11/openjdk-11_linux-x64_bin.tar.gz -o jdk.tar.gz
  - sh: curl http://download2.gluonhq.com/jpackager/11/jdk.packager-linux.zip -o java-packager.zip
  - sh: tar zxf jdk.tar.gz
  - sh: unzip -qq java-packager.zip -d java-packager
  - sh: export JAVA_HOME=$(pwd)/jdk-11
  - sh: export PATH=$JAVA_HOME/bin:$PATH
  - sh: cd tokentool-moulinette
  - ps: cd ..
  - ps: curl https://download.java.net/java/ga/jdk11/openjdk-11_windows-x64_bin.zip -o jdk.zip
  - ps: curl http://download2.gluonhq.com/jpackager/11/jdk.packager-windows.zip -o java-packager.zip
  - ps: unzip -qq jdk.zip
  - ps: unzip -qq java-packager.zip
  - ps: '[Environment]::SetEnvironmentVariable("JAVA_HOME", "$pwd\jdk-11")'
  - ps: mv jpackager.exe jdk-11/bin
  - ps: mv jdk.packager.jar jdk-11/jmods
  - ps: cd tokentool-moulinette
  - ./gradlew -version

build_script:
  - ./gradlew build
after_build:
#  - sh: if [[ $APPVEYOR_REPO_TAG == "true" ]]; then ./gradlew createBundle -PjavaPackagerPath=../java-packager/ else echo "Not creating deploy artifacts because this is not a tag build."; fi
  - sh: ./gradlew createBundle -PjavaPackagerPath=../java-packager/
  - ps: "& 'C:/Program Files (x86)/Inno Setup 6/Compil32.exe' /cc build/resources/main/application.iss"
  - ps: Start-Sleep -Seconds 120
  - ps: cp build/resources/main/Moulinette-*.exe build/bundle
artifacts:
- path: build/bundle/moulinette*.deb
  name: Moulinette-Linux
- path: build/bundle/Moulinette*.exe
  name: Moulinette-Windows
deploy:
- provider: GitHub
  description: Release build from AppVeyor
  auth_token: $(GITHUB_RELEASE_KEY)
  #artifact: Moulinette-Linux, Moulinette-Windows
  draft: false
  prerelease: true
  force_update: false
  on:
    APPVEYOR_REPO_TAG: true
on_success:
  - ps: Invoke-RestMethod $env:APPVEYOR_DISCORD_WEBHOOK_SCRIPT_URL -o send.ps1
  - ps: ./send.ps1 success $env:DISCORD_URL
on_failure:
  - ps: Invoke-RestMethod $env:APPVEYOR_DISCORD_WEBHOOK_SCRIPT_URL -o send.ps1
  - ps: ./send.ps1 failure $env:DISCORD_URL
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
